version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foodtravel
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
