version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: db

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && dockerize -wait tcp://db:5432 -timeout 1m && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foodtravel_0409
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_HOST: db
