version: 2.1

jobs:
  build:
    working_directory: ~/foodtravel
    docker:
      - image: circleci/ruby:3.1.4-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
          MYSQL_DATABASE: foodtravel_test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Wait for MySQL to be ready
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Setup MySQL
          command: |
            sudo mysql -u -proot -e "CREATE USER IF NOT EXISTS '${DATABASE_USERNAME}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';"
            sudo mysql -u -proot -e "GRANT ALL PRIVILEGES ON foodtravel_test.* TO '${DATABASE_USERNAME}'@'localhost';"
            sudo mysql -u -proot -e "FLUSH PRIVILEGES;"
      - run:
          name: Setup database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  rubocop:
    working_directory: ~/foodtravel
    docker:
      - image: circleci/ruby:3.1.4-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  deploy:
    working_directory: ~/foodravel
    docker:
      - image: circleci/ruby:3.1.4-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Deploy to Heroku
          command: |
            echo 'machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY' > ~/.netrc
            echo 'machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY' >> ~/.netrc
            chmod 600 ~/.netrc
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku main

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - rubocop
      - deploy:
          requires:
            - build
            - rubocop
          filters:
            branches:
              only: main
