version: 2.1

jobs:
  build:
    working_directory: ~/foodtravel
    docker:
      - image: cimg/ruby:3.1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  rubocop:
    working_directory: ~/foodtravel
    docker:
      - image: cimg/ruby:3.1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  deploy:
    working_directory: ~/foodravel
    docker:
      - image: cimg/ruby:3.1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.3.26
            bundle install
      - run:
          name: Deploy to Heroku
          command: |
            echo 'machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY' > ~/.netrc
            echo 'machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY' >> ~/.netrc
            chmod 600 ~/.netrc
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku main

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - rubocop
      - deploy:
          requires:
            - build
            - rubocop
          filters:
            branches:
              only: main
