version: 2.1

orbs:
  ruby: circleci/ruby@2.1.3
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.7-node
      - image: cimg/postgres:14.12
        environment:
          POSTGRES_USER: ${DATABASE_USERNAME}
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    steps:
      - run:
          name: Create and set permissions for /home/circleci/project
          command: |
            mkdir -p /home/circleci/project
            sudo chown -R circleci:circleci /home/circleci/project
            sudo chmod -R 755 /home/circleci/project
      - checkout
      - ruby/install-deps
      - node/install:
          node-version: '16.20.2'
      - node/install-packages:
          pkg-manager: yarn

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.7-node
      - image: cimg/postgres:14.12
        environment:
          POSTGRES_USER: ${DATABASE_USERNAME}
          POSTGRES_DB: foodtravel_test
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: ${DATABASE_USERNAME}
      PGPASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: test
    steps:
      - run:
          name: Create and set permissions for /home/circleci/project
          command: |
            mkdir -p /home/circleci/project
            sudo chown -R circleci:circleci /home/circleci/project
            sudo chmod -R 755 /home/circleci/project
      - checkout
      - ruby/install-deps
      - node/install:
          node-version: '16.20.2'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:migrate --trace
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
