version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.7
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.4.22
      - node/install:
          node-version: '16.20.2'
      - run:
          name: Install npm 8.x
          command: npm install -g npm@8
      - node/install-packages:
          pkg-manager: yarn

  test:
    docker:
      - image: cimg/ruby:2.7.7
      - image: circleci/postgres:11.7
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: blog_rails6_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ${DATABASE_PASSWORD}
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.4.22
      - node/install:
          node-version: '16.20.2'
      -run:
          name: Install npm 8.x
          command: npm install -g npm@8
      - node/install-packages: 
          pkg-manager: yarn
      -run:
        name: Verify NPM version
        command: npm -v
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: DB Initializing
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
            bundle exec rake db:schema:load
      - run:
          name: rspec
          command: |
            bundle exec rspec --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format documentation
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
