default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: db
  port: 5432

development:
  <<: *default
  database: foodtravel_development

test:
  <<: *default
  database: foodtravel_test

production:
  <<: *default
  database: foodtravel_production
